Вариант 4
(Методы):
1)замена критериев ограничениями;
2)взвешивание и объединение критериев;
3)формирование и сужение множества Парето;
4)анализ иерархий

Входные данные

In [53]:
from plotly.graph_objects import Figure, Table
from plotly.offline import iplot
import numpy as np


# Альтернативы
alternatives = ['Автострада', 'Шоссе', 'Грунтовка', 'Проселок']

# Критерии
criterions = ['Расстояние',
              'Качество покрытия',
              'Контроль',
              'Инфраструктура']

# Для матрицы оценок результатов
distanс = [2.,3.,6.,7.] # Чем больше расстояние, тем меньше оценка
quality = [8.,6.,2.,1.]
control = [1.,2.,5.,6.] # Чем больше контроль, тем меньше оценка
infrast = [7.,8.,3.,1.]


# Веса критериев
weights = [6.,8.,2.,4.]
# Нормализация списка весов критериев
weights = [w / 10 for w in weights]

# Матрица оценок для альтернатив
a_matrix = np.array([distanс,
            quality,
            control,
            infrast], dtype=float)
print(a_matrix)

# Вывод изначальной таблицы оценок
fig_beg = Figure(data=[
    Table(
        header=dict(values=['Альтернативы\Критерии'] + criterions),
        cells=dict(
            values=[
                alternatives,
                distanс,
                quality,
                control,
                infrast
            ]),
    )])
iplot(fig_beg)

# Точность после запятой
okr = 5

# # Нормировка матрицы оценок (все столбцы)
# # Цикл по столбикам (критериям)
# for j, cr in enumerate(criterions):
#
#     min_val = min(a_matrix[j])
#     max_val = max(a_matrix[j])
#
#     # Цикл по строчкам (значения критериев альтернатив)
#     for i, al in enumerate(alternatives):
#         a_matrix[j][i] = round((a_matrix[j][i] - min_val) / (max_val - min_val), okr)
#
# # Вывод нормализованной таблицы
# fig_norm = Figure(data=[
#     Table(
#         header=dict(values=['Альтернативы\Критерии'] + criterions),
#         cells=dict(
#             values=[
#                 alternatives,
#                 a_matrix[0],
#                 a_matrix[1],
#                 a_matrix[2],
#                 a_matrix[3]
#             ]),
#     )])
# iplot(fig_norm)

[[2. 3. 6. 7.]
 [8. 6. 2. 1.]
 [1. 2. 5. 6.]
 [7. 8. 3. 1.]]


Метод замены критериев ограничениями

In [56]:
# Пусть главный критерий - Расстояние

# Нормировка матриц оценок (кроме столбца главного критерия)
# Цикл по столбикам (критериям)
for j, cr in enumerate(criterions):
    # Если это главный критерий, то пропустить
    if cr == 'Расстояние':
        continue

    lev = None
    # Минимально допустимые уровни для остальных критериев
    match(cr):
        case 'Качество покрытия':
            lev = 0.3
        case 'Контроль':
            lev = 0.1
        case 'Инфраструктура':
            lev = 0.2

    min_val = min(a_matrix[j])
    max_val = max(a_matrix[j])

    # Цикл по строчкам (значения критериев альтернатив)
    for i, al in enumerate(alternatives):
        a_matrix[j][i] = round((a_matrix[j][i] - min_val) / (max_val - min_val), okr)
        # Оставить только приемлемые значения
        if a_matrix[j][i] < lev:
            a_matrix[j][i] = 0.0

# Вывод таблицы
fig = Figure(data=[
    Table(
        header=dict(values=['Альтернативы\Критерии'] + criterions),
        cells=dict(
            values=[
                alternatives,
                a_matrix[0],
                a_matrix[1],
                a_matrix[2],
                a_matrix[3]
            ]),
    )])
iplot(fig)